"""Updated some models

Revision ID: 87bfc381ac23
Revises: b1b8820e2fea
Create Date: 2025-07-26 21:15:43.359097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87bfc381ac23"
down_revision = "b1b8820e2fea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
