"""add_admin_field_to_users

Revision ID: 6431384972b4
Revises: e243d9bac940
Create Date: 2025-07-28 18:16:36.970982

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6431384972b4"
down_revision = "e243d9bac940"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=True, comment="Admin user flag"),
    )
    # Set default value for existing records
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    # Now make it non-nullable
    op.alter_column("users", "is_admin", nullable=False)
    op.alter_column(
        "users",
        "access_status",
        existing_type=sa.VARCHAR(length=20),
        comment="Access level: waiting_list, early_access, full_access",
        existing_nullable=False,
        existing_server_default=sa.text("'waiting_list'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "access_status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Access level: waiting_list, early_access, full_access",
        existing_nullable=False,
        existing_server_default=sa.text("'waiting_list'::character varying"),
    )
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
