"""add contact fields and account status to users

Revision ID: ca160596cde0
Revises: 6431384972b4
Create Date: 2025-07-28 23:47:43.762579

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca160596cde0"
down_revision = "6431384972b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "phone",
            sa.String(length=50),
            nullable=True,
            comment="Phone number for contact",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "company_name",
            sa.String(length=255),
            nullable=True,
            comment="Company/Organization name",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "industry",
            sa.String(length=100),
            nullable=True,
            comment="Industry/Business type",
        ),
    )
    # Add has_account column with default value first
    op.add_column(
        "users",
        sa.Column(
            "has_account",
            sa.Boolean(),
            nullable=True,
            comment="Whether user completed full account creation",
        ),
    )
    # Set default value for existing users (assume they have accounts if they exist)
    op.execute("UPDATE users SET has_account = true WHERE has_account IS NULL")
    # Now make it non-nullable
    op.alter_column("users", "has_account", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_account")
    op.drop_column("users", "industry")
    op.drop_column("users", "company_name")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
