"""Updated some models

Revision ID: 8ac94ea6fcfd
Revises: 4bad48682f30
Create Date: 2025-07-25 14:03:25.084888

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ac94ea6fcfd"
down_revision = "4bad48682f30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
