"""Updated some models

Revision ID: b1b8820e2fea
Revises: 8ac94ea6fcfd
Create Date: 2025-07-25 14:07:06.783610

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1b8820e2fea"
down_revision = "8ac94ea6fcfd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
