"""add_demo_tracking_fields

Revision ID: 627c9dc8a8fc
Revises: ca160596cde0
Create Date: 2025-07-29 13:15:40.829042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627c9dc8a8fc'
down_revision = 'ca160596cde0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('demo_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('demo_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('demo_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('current_solution', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('demo_prep_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('follow_up_reminders', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('user_qualification_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_qualification_notes')
    op.drop_column('users', 'follow_up_reminders')
    op.drop_column('users', 'demo_prep_notes')
    op.drop_column('users', 'current_solution')
    op.drop_column('users', 'company_size')
    op.drop_column('users', 'demo_completed_at')
    op.drop_column('users', 'demo_completed')
    op.drop_column('users', 'demo_scheduled_at')
    # ### end Alembic commands ###